In [57]:
import numpy as np

In [58]:
def softmax(z):
    return np.exp(z) / np.sum(np.exp(z), axis=0)

In [59]:
z = np.array([[-1, 3, 10],
             [5, 2, -4],
             [3,-5,15]])
s = softmax(z)
s

array([[2.17852136e-03, 7.30879336e-01, 6.69285089e-03],
       [8.78878243e-01, 2.68875482e-01, 5.56529773e-09],
       [1.18943236e-01, 2.45182703e-04, 9.93307144e-01]])

In [60]:
def softmax1(Z):
    Z_exp = np.exp(Z - np.max(Z, axis=0))
    return Z_exp / np.sum(Z_exp, axis=0)

In [61]:
p = softmax1(z)
print(p)    

[[2.17852136e-03 7.30879336e-01 6.69285089e-03]
 [8.78878243e-01 2.68875482e-01 5.56529773e-09]
 [1.18943236e-01 2.45182703e-04 9.93307144e-01]]


In [62]:
y = np.array([2, 1, 0])
y

array([2, 1, 0])

In [67]:
print(p[y, np.arange(p.shape[1])])

[0.11894324 0.26887548 0.00669285]


In [68]:
print(y)
print(np.arange(p.shape[1]))

[2 1 0]
[0 1 2]


In [72]:
#training loss
np.mean(-np.log(p[y, np.arange(p.shape[1])]))

2.816443721055773